package:
  name: linkage2allegro
  version: "2017.1"

source:
  url: https://github.com/BioTools-Tek/linkage-converter/archive/master.zip
  md5: 23ba85864f197b0bc6bde245d06648a7

build:
  number: 1

requirements:
  build:
    - python

  run:
    - python
    - future

test:
  commands:
    - linkage2allegro 2>&1 | grep descentfile

about:
  home: https://github.com/BioTools-Tek/linkage-converter
  license: GPL3
  summary: linkage2allegro converts between the output linkage formats of Merlin, Simwalk, Genehunter, and Swiftlink into Allegro.
