package:
  name: linkage2allegro
  version: 2

source:
  url: https://github.com/BioTools-Tek/linkage-converter/archive/master.zip
  md5: d110247846de8ee433bda2190b530959
    

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python

test:
  commands:
    - linkage2allegro 2>&1 | grep descentfile

about:
  home: https://github.com/BioTools-Tek/linkage-converter
  license: GPL3
  summary: linkage2allegro converts between the output linkage formats of Merlin, Simwalk, Genehunter, and Swiftlink into Allegro.
