{% set name = "uclust" %}
{% set version = "1.2.22" %}
{% set revision = "q" %}


package:
  name: {{ name }}
  version: {{ version }}{{ revision }}

build:
  number: 0
  skip: false

source:
  url: http://drive5.com/{{ name }}/{{ name }}{{ revision }}{{ version }}_i86linux64
  md5: d696e0d0b744605227deaaa6e9184061

test:
  commands:
    - uclust --version
about:
  home: https://drive5.com/usearch/manual/uclust_algo.html
  summary: 'Divides a set of sequences into clusters'
  license: 'Following PyNAST License: BSD License'
