{% set name = "uclust" %}
{% set version = "1.2.22" %}
{% set revision = "q" %}

package:
  name: {{ name }}
  version: {{ version }}{{ revision }}

build:
  number: 0
  skip: false

source:
  url: http://drive5.com/{{ name }}/{{ name }}{{ revision }}{{ version }}_i86linux64 # [linux]
  md5: d696e0d0b744605227deaaa6e9184061 # [linux]
  url: http://drive5.com/{{ name }}/{{ name }}{{ revision }}{{ version }}_i86darwin64 # [osx]
  md5: a37e7284900ebded0959029ec19622d1 # [osx]

test:
  commands:
    - uclust --version

about:
  home: https://drive5.com/usearch/manual/uclust_algo.html
  summary: 'Divides a set of sequences into clusters'
  license: 'Following PyNAST License: BSD License'
