{% set name = "structureHarvester" %}
{% set version = "0.6.94" %}
{% set commit = "e15952601b946267ce566df6ff0dd56df5c8b8f6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ commit }}.zip
  md5: 41ce1a230ba9a4ee9b7dca2dd63cc700
  url: https://github.com/dentearl/structureHarvester/archive/{{ commit }}.zip

build:
  number: 0
  #skip: True  # [not py27]

requirements:
  build:
    - python >=2.7,<3
  run:
    - python >=2.7,<3

test:
    commands:
        - structureHarvester.py --version 2> /dev/stdout 2> /dev/stdout | grep "{{ version }}"
about:
    home: 'http://alumni.soe.ucsc.edu/~dearl/software/structureHarvester/'
    license: MIT
    summary: "structureHarvester.py is a Python script capable of extracting all the relevant data from STRUCTURE results files"
