{% set version = "0.2.1" %}

package:
  name: quasitools
  version: {{ version }}

source:
  fn: quasitools-{{ version }}.tar.gz
  url: https://github.com/phac-nml/quasitools/archive/v{{ version }}.tar.gz
  md5: bf3c01af9c30ee5e0add80a141f8678c

build:
  number: 1
  entry_points:
    - quasitools = quasitools.cli:cli

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - samtools ==0.1.19
    - pysam ==0.9
    - click
    - biopython
    - bowtie2

test:
  commands:
    - quasitools --help

about:
  home: https://github.com/phac-nml/quasitools/
  license: Apache License, Version 2.0
  summary: Quasitools is a collection of tools for analysing Viral Quasispecies

extra:
  container:
    # click requires a unicode locale when used with Python 3
    # extended-base generates en_US.UTF-8 locale and sets LC_ALL, LANG properly
    extended-base: true  # [py3k]
